import Navigation from "@/components/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>{children}</main>

        <footer>Copywright by the Wild Oasis</footer>
      </body>
    </html>
  );
}
